import Image from "next/image";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="bg-blue-500 p-10">
      <h1>hello chat</h1>
    </div>
  );
}
